### ISSUE TITLE
Provide a test helper for fixtures

### ISSUE THREAD

**Issue by amiel** [amiel/bitmasker#9]
This works, but it would be nice to have something simpler:

```yaml
<% bitmask = Collaborator.notifications_scope.bitmask_attributes %>

user:
  notifications_mask: <%= Bitmask.new(bitmask, 'receive_timeline_notifications' => true).to_i %>
```
